sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
  
menu_backend:
  url:   /menu_backend/:id
  param: { module: MenuBackend, action: index }

menu_backend_root:
  url:   /menu_backend
  param: { module: MenuBackend, action: index }

# default rules
homepage:
  url:   /
  param: { module: Home, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

